---
- name: Generate commands for Cleaning Device
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Generate commands for device cleaning (except SONiC)
      template:
        src: "{{ template_name }}"
        dest: /var/tmp/debug-{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os != "sense.sonic.sonic"

    - name: Generate commands for device cleaning (only SONiC)
      template:
        src: "{{ template_name }}"
        dest: /var/tmp/debug-{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sense.sonic.sonic"
