---
- name: Get running configuration
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
  - name: Gather Dell OS 9 Facts
    sense.dellos9.dellos9_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.dellos9.dellos9"

  - name: Gather Dell OS 10 Facts
    sense.dellos10.dellos10_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.dellos10.dellos10"

  - name: Gather Arista EOS Facts
    sense.aristaeos.aristaeos_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.aristaeos.aristaeos"

  - name: Gather Azure SONiC Facts
    sense.sonic.sonic_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.sonic.sonic"

  - name: Gather RARE FreeRTR Facts
    sense.freertr.freertr_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.freertr.freertr"

  - name: Gather all Cisco NX facts
    sense.cisconx9.cisconx9_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.cisconx9.cisconx9"

  - name: Gather FRR Facts
    sense.frr.frr_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.frr.frr"

  - name: Gather Juniper Junos Facts
    sense.junos.junos_facts:
      gather_subset: all
    register: facts
    when: ansible_network_os is defined and ansible_network_os == "sense.junos.junos"
