---
- name: Execute Ping
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: Build Config Templates for Ping
      template:
        src: "{{ template_name_ping }}"
        dest: /var/tmp/ping_{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os != "sense.sonic.sonic" and ansible_network_os != "sense.frr.frr"

    - name: Push Dell OS 9 Ping Request
      sense.dellos9.dellos9_command:
        src: /var/tmp/ping_{{ inventory_hostname }}.conf
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
      when: ansible_network_os is defined and ansible_network_os == 'sense.dellos9.dellos9'

    - name: Push Dell OS 10 Ping Request
      sense.dellos10.dellos10_command:
        src: /var/tmp/ping_{{ inventory_hostname }}.conf
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
      when: ansible_network_os is defined and ansible_network_os == 'sense.dellos10.dellos10'

    - name: Push Arista EOS Request
      sense.aristaeos.aristaeos_command:
        src: /var/tmp/ping_{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sense.aristaeos.aristaeos"

    - name: Push Cisco NX Ping Request
      sense.cisconx9.cisconx9_command:
        src: /var/tmp/ping_{{ inventory_hostname }}.conf
        provider:
          host: "{{ ansible_host }}"
          timeout: 300
      when: ansible_network_os is defined and ansible_network_os == "sense.cisconx9.cisconx9"

    - name: Build Ping templates for SONiC
      template:
        src: "{{ template_name_ping }}"
        dest: /tmp/ping_{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sense.sonic.sonic"

    - name: Push Azure Sonic Ping
      sense.sonic.sonic_command:
        sonic_debug: False
        sonic_ping: /tmp/ping_{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sense.sonic.sonic"

    - name: Build Ping templates for FRR
      template:
        src: "{{ template_name_ping }}"
        dest: /tmp/ping_{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sense.frr.frr"

    - name: Push Azure Sonic Ping
      sense.frr.frr_command:
        frr_debug: False
        frr_ping: /tmp/ping_{{ inventory_hostname }}.conf
      when: ansible_network_os is defined and ansible_network_os == "sense.frr.frr"
